name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test build
    runs-on: ubuntu-22.04
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          yarn
          yarn build
